import { createShellApp } from "./shell-core.js";

const localeText = {
  zh: {
    pageTitle: "AI助手充值系统",
    brandTitle: "AI助手充值系统",
    openChatgpt: "第一步：打开ChatGPT",
    openAuthSession: "第二步：打开AuthSession页面",
    guideTitle: "操作指南",
    guideStep1Title: "卡密查询",
    guideStep1Body: "请输入您的CDKEY并点击立即验证。",
    guideStep2Title: "确认登录状态",
    guideStep2Body: "请确认您已在 chatgpt.com 登录账户，然后选择下一步操作。",
    guideStep3Title: "提交充值信息",
    guideStep3Body: "点击打开AuthSession页面按钮，将页面内的所有内容复制在session_info输入框内，点击开始激活按钮。",
    cdkeyLabel: "请输入CDKEY",
    cdkeyPlaceholder: "例如：5S8F-S888G-5G5G-55HH",
    checkButton: "立即验证",
    activateButton: "开始激活",
    sessionLabel: "session_info（JSON）",
    forceRechargeLabel: "放弃剩余会员时间，强制充值",
    sessionPlaceholder:
      '{"account":{"id":"user-xxx","planType":"free"},"accessToken":"ey...","user":{"email":"test@example.com"}}',
    checkResultTitle: "查验结果",
    activateResultTitle: "激活结果",
    notRequested: "尚未请求",
    checkLoading: "请求状态...",
    activateLoading: "激活中...",
    needCdkeyForCheck: "请输入CDKEY后再执行查验。",
    needCdkeyForActivate: "请先输入CDKEY。",
    needSessionInfo: "激活需要填写 session_info。",
    invalidSession: "session_info 不是合法的 JSON，请检查后重传。",
    requestFailed: "无法连接接口，请稍后重试。",
    activateFailed: "激活失败，请稍后重试。",
    notFoundCdkey: "未检测到CDKEY",
    noTextResult: "未提取到可展示的文本结果。",
  },
  en: {
    pageTitle: "AI Assistant Recharge System",
    brandTitle: "AI Assistant Recharge System",
    openChatgpt: "Step 1: Open ChatGPT",
    openAuthSession: "Step 2: Open AuthSession Page",
    guideTitle: "Guide",
    guideStep1Title: "Alias CDKEY Check",
    guideStep1Body: "Enter your alias CDKEY and click Verify.",
    guideStep2Title: "Confirm Login Status",
    guideStep2Body: "Make sure you are logged in to chatgpt.com before continuing.",
    guideStep3Title: "Submit Recharge Info",
    guideStep3Body: "Click Open AuthSession Page, then copy all page content into the session_info input.",
    cdkeyLabel: "Enter Alias CDKEY",
    cdkeyPlaceholder: "Example: 5S8F-S888G-5G5G-55HH",
    checkButton: "Verify",
    activateButton: "Activate",
    sessionLabel: "session_info (JSON)",
    forceRechargeLabel: "Force recharge (forfeit remaining time)",
    sessionPlaceholder:
      '{"account":{"id":"user-xxx","planType":"free"},"accessToken":"ey...","user":{"email":"test@example.com"}}',
    checkResultTitle: "Verification Result",
    activateResultTitle: "Activation Result",
    notRequested: "No request yet",
    checkLoading: "Checking...",
    activateLoading: "Activating...",
    needCdkeyForCheck: "Enter alias CDKEY before verification.",
    needCdkeyForActivate: "Enter alias CDKEY first.",
    needSessionInfo: "session_info is required for activation.",
    invalidSession: "session_info must be valid JSON.",
    requestFailed: "Unable to reach API. Please retry.",
    activateFailed: "Activation failed. Please retry.",
    notFoundCdkey: "CDKEY not detected",
    noTextResult: "No displayable text result found.",
  },
};

createShellApp(localeText);
