import { createShellApp } from "./shell-core.js";

const localeText = {
  zh: {
    pageTitle: "ChatGPT 礼品兑换中心",
    brandTitle: "ChatGPT 礼品兑换中心",
    heroSubline: "安全、快速、独立的账号兑换服务",
    guideTitle: "操作向导",
    guideIntro: "按顺序完成验证与兑换，提交后请耐心等待返回结果。",
    guideStep1Title: "核对兑换码",
    guideStep1Body: "输入 CDKEY 后点击验证，确认卡密状态与礼包信息。",
    guideStep2Title: "打开 ChatGPT",
    guideStep2Body: "保持目标账号处于登录状态，再继续下一步操作。",
    guideStep3Title: "获取会话信息",
    guideStep3Body: "打开 AuthSession 页面，把完整 JSON 内容复制到下方输入框。",
    guideStep4Title: "提交兑换",
    guideStep4Body: "确认信息无误后点击开始激活，返回成功即代表兑换已提交。",
    openChatgpt: "打开 ChatGPT",
    openAuthSession: "打开 AuthSession",
    redeemTitle: "CDK 兑换",
    redeemSubline: "支持先验证再兑换，也可直接提交账号会话完成激活。",
    cdkeyLabel: "输入兑换 CDKEY",
    cdkeyPlaceholder: "例如：5S8F-S888G-5G5G-55HH",
    checkButton: "验证",
    activateButton: "开始激活",
    sessionLabel: "输入会话信息",
    sessionPlaceholder:
      '{"account":{"id":"user-xxx","planType":"free"},"accessToken":"ey...","user":{"email":"test@example.com"}}',
    forceRechargeLabel: "放弃剩余会员时间，强制充值",
    checkResultTitle: "验证结果",
    checkResultHint: "仅显示当前提交对应的可读文本结果。",
    activateResultTitle: "兑换结果",
    activateResultHint: "激活完成后会展示最终状态与关键信息。",
    footerText: "© 2026 兑换服务中心. 使用本服务即表示您已了解相关规则。",
    notRequested: "尚未请求",
    checkLoading: "验证中...",
    activateLoading: "提交中...",
    needCdkeyForCheck: "请先输入 CDKEY 再验证。",
    needCdkeyForActivate: "请先输入 CDKEY。",
    needSessionInfo: "请输入 session_info。",
    invalidSession: "session_info 不是合法 JSON。",
    requestFailed: "接口连接失败，请稍后重试。",
    activateFailed: "兑换提交失败，请稍后再试。",
    notFoundCdkey: "未检测到CDKEY",
    noTextResult: "未提取到可展示的文本结果。",
  },
  en: {
    pageTitle: "ChatGPT Redeem Center",
    brandTitle: "ChatGPT Redeem Center",
    heroSubline: "Fast and discreet account redeem service.",
    guideTitle: "Walkthrough",
    guideIntro: "Complete verification and redeem in order, then wait for the final status.",
    guideStep1Title: "Verify Your Code",
    guideStep1Body: "Enter the CDKEY and check its availability before redeeming.",
    guideStep2Title: "Open ChatGPT",
    guideStep2Body: "Keep the target account signed in before moving forward.",
    guideStep3Title: "Fetch Session Data",
    guideStep3Body: "Open the AuthSession page and paste the full JSON into the form.",
    guideStep4Title: "Submit Redeem",
    guideStep4Body: "Review the details and submit the redeem request.",
    openChatgpt: "Open ChatGPT",
    openAuthSession: "Open AuthSession",
    redeemTitle: "Redeem CDK",
    redeemSubline: "Verify first or submit directly once the account session is ready.",
    cdkeyLabel: "Enter Redeem CDKEY",
    cdkeyPlaceholder: "Example: 5S8F-S888G-5G5G-55HH",
    checkButton: "Verify",
    activateButton: "Redeem Now",
    sessionLabel: "Session Payload",
    sessionPlaceholder:
      '{"account":{"id":"user-xxx","planType":"free"},"accessToken":"ey...","user":{"email":"test@example.com"}}',
    forceRechargeLabel: "Force redeem and forfeit remaining membership time",
    checkResultTitle: "Verification Result",
    checkResultHint: "Only readable text results for the current request are shown.",
    activateResultTitle: "Redeem Result",
    activateResultHint: "The final activation status appears here after submission.",
    footerText: "© 2026 Redeem Service Center. By using this service, you accept the operating rules.",
    notRequested: "No request yet",
    checkLoading: "Verifying...",
    activateLoading: "Submitting...",
    needCdkeyForCheck: "Enter the CDKEY before verification.",
    needCdkeyForActivate: "Enter the CDKEY first.",
    needSessionInfo: "session_info is required.",
    invalidSession: "session_info must be valid JSON.",
    requestFailed: "Unable to reach the API. Retry later.",
    activateFailed: "Redeem failed. Retry later.",
    notFoundCdkey: "CDKEY not detected",
    noTextResult: "No displayable text result found.",
  },
};

createShellApp(localeText);

const themeToggle = document.getElementById("theme-toggle");

themeToggle?.addEventListener("click", () => {
  const current = document.body.dataset.theme === "night" ? "night" : "day";
  document.body.dataset.theme = current === "night" ? "day" : "night";
});
