name = "alias-service"
main = "src/worker.js"
compatibility_date = "2026-04-01"

# Fill these after creating KV namespace
[[kv_namespaces]]
binding = "ALIAS_MAP"
id = "d554404c718c481ab8ccddec3d1f608e"
preview_id = "d554404c718c481ab8ccddec3d1f608e"

[[durable_objects.bindings]]
name = "ACTIVATION_GATE"
class_name = "ActivationGate"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ActivationGate"]
